<?php

namespace ContainerGspGErf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E_LigjkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E.Ligjk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E.Ligjk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'question' => ['privates', '.errored..service_locator.E.Ligjk.App\\Entity\\Question', NULL, 'Cannot autowire service ".service_locator.E.Ligjk": it references class "App\\Entity\\Question" but no such service exists.'],
            'quizzHistoryRepository' => ['privates', 'App\\Repository\\QuizzHistoryRepository', 'getQuizzHistoryRepositoryService', true],
        ], [
            'question' => 'App\\Entity\\Question',
            'quizzHistoryRepository' => 'App\\Repository\\QuizzHistoryRepository',
        ]);
    }
}
