<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGspGErf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGspGErf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGspGErf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGspGErf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGspGErf\App_KernelDevDebugContainer([
    'container.build_hash' => 'GspGErf',
    'container.build_id' => '10bd17fe',
    'container.build_time' => 1678441493,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGspGErf');
